### ISSUE TITLE
Fix Definition for Module

### ISSUE THREAD

**Issue by ikiril01** [mitre-attack/attack-datasources#52]
https://github.com/mitre-attack/attack-datasources/blob/0cde745a308bd4b2e12ec4dba6cbf3de5406ea5a/contribution/module.yml#L2

There's a minor typo (`linkiable`) in the definition text, and I think the overall definition can be modified a little for accuracy since PE/ELF/Mach-O encompass both executables and libraries. I would suggest:

`Information about module files consisting of one or more classes and interfaces, such as portable executable (PE) format executables/dynamic link libraries (DLL), executable and linkable format (ELF) executables/shared libraries, and Mach-O format executables/shared libraries.`

**Comment by jcwilliamsATmitre** [comment]
Thanks @ikiril01!!!!
