### ISSUE TITLE
Small loading error

### ISSUE THREAD

**Issue by Sascha90** [mitre-attack/attack-datasources#57]
When I tried to load logon_session.yml I have gotten the error

mapping values are not allowed here 
at line 22, column 72.

The offending line is
    description: Data and information that describe a logon session (ex: logon type) and activity within it.

It can be solved by removing the space between the colon and logon
    description: Data and information that describe a logon session (ex:logon type) and activity within it.

Best regards,
Sascha90

**Comment by jcwilliamsATmitre** [comment]
Great catch, sorry about that!

**Comment by Sascha90** [comment]
No problem 👍
